### ISSUE TITLE
Isn't working for me

### ISSUE THREAD

**Issue by deathgaze** [swimit/swim-academy#2]
Gave this a run this evening at home to find that the basics example doesn't seem to work. It looks like the browser can connect to the server ok, but the the server never produces any data.

**Comment by ajay-gov** [comment]
You have to run the "gradle clientRun" [command](https://github.com/swimit/swim-academy/tree/master/basics/services#run-the-client). This sends simulated data to the server which is then displayed by the UI.

**Comment by ajay-gov** [comment]
Can you confirm that you are seeing some messages on the console when you run 'gradle run' and 'gradle runClient. 

On the console where you have the 'gradle run' command, you should see log messages like this:
_"Listening on port 9001
addLatest lane received value: 0
latest lane set with value: 0
...."_

On the console where you have the 'gradle runClient' command, you should see log messages like this:
_"Received latest value 
Received latest value 0
Updated history (key, value): (1530322568155:0)
Received latest value
..."_ 

If you are receiving the above then the client and server are working then it's an html issue. Regarding the html- Which browser (and OS) are you using? Could you try it on a chrome, firefox (latest version) or safari browser?

thanks

**Comment by deathgaze** [comment]
A-hah! After cycling the server process off and on, it started to work. :) Thanks...
